config/routes.rb
Rails.application.routes.draw do
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    after_create_commit { broadcast_append_to 'events' }
end

app/models/game_time.rb
class GameTime < ApplicationRecord
    after_update_commit { broadcast_replace_to 'game_time' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @events = Event.all
    @game_times = GameTime.all
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def game_time
    render json: DoomFortress::GameService.get_game_time()
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:event_id, :topic, :timestamp, :event_type, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def getTemplate(topic, value, event_type)
    json = JSON.parse(value)
    case topic
    when"status"
      return {source: "jesus", action: json["status"], target: "galaxy"}
    when"mining"
      return {source: "robot_alive", action: "mining", target: json["resourceType"]}
    when"fighting"
      return {source: "robot_alive", action: "fighting", target: "robot"}
    when"moving"
      return {source: "robot_alive", action: "moving", target: "universe"}
    when"trades"
      event_data = event_type.split('-')
      if event_data[0] == 'buy'
        return {source: "player", action: "buy", target: event_data[1]}
      else
        return {source: "player", action: "sell", target: event_data[1]}
      end
    when"regeneration"
      return {source: "robot_alive", action: "regeneration", target: "robot"}
    when"blocking"
      return {source: "robot_alive", action: "blocking", target: "robot"}
    when"robot-destroyed"
      return {source: "robot_alive", action: "fighting", target: "robot_dead"}
    else
      return {source: "robot_alive", action: "notfound", target: "notfound"}
    end
  end
end

app/helpers/scoreboards_helper.rb
module ScoreboardsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/events/_event.html.erb
<%= turbo_frame_tag dom_id(event) do %>
  <%= link_to event, data: { turbo: false } do %>
    <div class='bg-gray-500 max-w-md rounded-lg min-w-[50%] m-2 px-1'>
      <div class='flex flex-row justify-around'>
        <img class='max-w-[25%] p-4' src="/images/<%= getTemplate(event.topic, event.value, event.event_type)[:source] %>.png" alt="robot">
        <img class='max-w-[25%] p-4' src="/images/<%= getTemplate(event.topic, event.value, event.event_type)[:action] %>.png" alt="<%= event.topic %>">
        <img class='max-w-[25%] p-4' src="/images/<%= getTemplate(event.topic, event.value, event.event_type)[:target] %>.png">
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, class: "contents") do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, class: "block shadow rounded-md border border-gray-200 outline-none text-black px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :topic %>
    <%= form.text_field :topic, class: "block shadow rounded-md border border-gray-200 outline-none text-black px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :timestamp %>
    <%= form.text_field :timestamp, class: "block shadow rounded-md border border-gray-200 outline-none text-black px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :event_type %>
    <%= form.text_field :event_type, class: "block shadow rounded-md border border-gray-200 outline-none text-black px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :value %>
    <%= form.text_area :value, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none text-black px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing event</h1>

  <%= render "form", event: @event %>

  <%= link_to "Show this event", @event, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to events", events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/events/index.html.erb
<div class='border-b-2 flex justify-center'>
  <div class='flex flex-column'>
    <%= turbo_stream_from "game_time" %>
    <%= render @game_times %>
  </div>
</div>
<div class="w-full p-0 m-0 mx-auto h-full">
  <% if notice.present? %>
  <p class="bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mx-3">
    <h1 class="font-bold text-4xl">Events</h1>
    <%= link_to 'New event', new_event_path, class: "rounded-lg py-1 px-1 bg-orange-600 text-white block font-medium" %>
  </div>

  <%= turbo_stream_from "events" %>
  <div id="events" class="min-w-full flex flex-wrap">
    <%= render @events %>
  </div>
</div>

app/views/events/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New event</h1>

  <%= render "form", event: @event %>

  <%= link_to 'Back to events', events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block text-black font-medium" %>
</div>

app/views/events/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
      <%= render @event %>
    <div class='bg-gray-500 max-w-md rounded-lg min-w-[50%] m-2 px-1'>
    <h1>Debug information</p>
      <p>Event ID: <%= @event.event_id%></p>
      <p>Topic: <%= @event.topic%></p>
      <p>Timestamp: <%= @event.timestamp%></p>
      <p>Event Type: <%= @event.event_type%></p>
      <p>Value: <%= @event.value%></p>

    </div>

    <%= link_to 'Edit this event', edit_event_path(@event), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium text-black" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this event', event_path(@event), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium text-black" %>
    </div>
    <%= link_to 'Back to events', events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium text-black" %>
  </div>
</div>

app/views/game_times/_game_time.html.erb
<%= turbo_frame_tag dom_id(game_time) do %>
    <span class='flex flex-row font-doom text-4xl'> 
        <p class='px-2' id='time'>Time: <%= game_time.time %> </p>
        <p class='px-2' id='roundcount'>Round No: <%= game_time.round_count %> </p>
        <p class='px-2 id='roundtime'> Time left: <%= game_time.round_time %> </p>
    </span>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoomFortress</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="http://fonts.cdnfonts.com/css/doom-2016-left" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-doom-9000'>
    <main class="text-gray-100 ">
      <%= yield %>
    </main>
  </body>
</html>